#!/usr/bin/env python3
"""Package the public harness and explicitly selected tasks as a portable suite kit.

The kit holds tracked harness runtime files (from git ls-files, filtered by an
allowlist), the named task directories from --tasks-dir under tasks/, a
generated run-suite.sh that runs exactly those tasks, and suite-manifest.json
with task IDs and content hashes. solution/ is left out unless
--include-solutions is given. Nothing is fetched and no task is run.

Usage: python3 scripts/package-suite.py --tasks-dir DIR --output kit.tar.gz ID [ID ...]
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from rangebench.identity import task_identity  # noqa: E402

MANIFEST = "suite-manifest.json"
RUN_SCRIPT = "run-suite.sh"
HARNESS_FILES = {"pyproject.toml", "README.md", "LICENSE", "configs/local-example.toml"}
HARNESS_DIRS = ("attacker/",)
SAFE_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
# Local state and caches, dropped anywhere in a task.
SKIP_DIRS = {".git", ".audit", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
SKIP_DIRS |= {".venv", "venv", ".idea", ".vscode"}
SKIP_FILES = {".DS_Store", ".git"}
SKIP_SUFFIXES = (".pyc", ".pyo", ".swp")
# Run output, dropped at a task's top level only.
SKIP_TOP_DIRS = {"results", "logs"}
# Credential and env files are an error, not a silent drop: removing one could break a task.
SECRET_FILES = {".env", ".netrc", ".git-credentials", ".pypirc", ".npmrc", ".dockercfg"}

RUN_TEMPLATE = """\
#!/bin/sh
# Generated by scripts/package-suite.py. Runs exactly the packaged tasks.
# Add run options as arguments. Name the API key variable with --api-key-env;
# never put a key on the command line.
set -eu
kit=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$kit"
PYTHONPATH="$kit"
export PYTHONPATH
exec python3 -P -m rangebench run {ids} "$@"
"""


class PackageError(Exception):
    """A packaging request that was refused."""


def _git(root: Path, *args: str) -> str:
    try:
        out = subprocess.run(
            ["git", "-C", str(root), *args], capture_output=True, text=True, timeout=30
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise PackageError(f"git {args[0]} failed: {exc}") from None
    if out.returncode != 0:
        raise PackageError(f"git {args[0]} failed; the harness must be a git checkout")
    return out.stdout


def _harness_allowed(rel: str) -> bool:
    if rel in HARNESS_FILES or rel.startswith(HARNESS_DIRS):
        return True
    return rel.startswith("rangebench/") and rel.count("/") == 1 and rel.endswith(".py")


def harness_files(root: Path) -> list[str]:
    """Tracked, allowlisted harness runtime files, relative to root."""
    files = sorted(rel for rel in _git(root, "ls-files", "-z").split("\0") if _harness_allowed(rel))
    for rel in files:
        path = root / rel
        if path.is_symlink() or not path.is_file():
            raise PackageError(f"harness file {rel} is missing or not a regular file")
    if "rangebench/__main__.py" not in files:
        raise PackageError("harness package rangebench/ is not tracked")
    return files


def harness_commit(root: Path, files: list[str]) -> str | None:
    """HEAD commit when the packaged harness files match it, else None."""
    if _git(root, "status", "--porcelain", "--", *files).strip():
        print("note: harness files differ from HEAD; harness_commit is null", file=sys.stderr)
        return None
    return _git(root, "rev-parse", "HEAD").strip()


def select_tasks(tasks_dir: Path, task_ids: list[str]) -> list[tuple[str, Path]]:
    """Validate explicit task IDs as direct child directories of tasks_dir."""
    if not task_ids:
        raise PackageError("name at least one task ID")
    if not tasks_dir.is_dir():
        raise PackageError("--tasks-dir is not a directory")
    base = tasks_dir.resolve()
    selected: list[tuple[str, Path]] = []
    for tid in task_ids:
        if not SAFE_NAME.fullmatch(tid):
            raise PackageError(f"invalid task ID {tid!r}")
        if tid in (s[0] for s in selected):
            raise PackageError(f"task {tid} named twice")
        path = base / tid
        if path.is_symlink():
            raise PackageError(f"task {tid} is a symlink")
        if not path.is_dir():
            raise PackageError(f"task {tid} not found in --tasks-dir")
        spec = path / "task.json"
        if spec.is_symlink() or not spec.is_file():
            raise PackageError(f"task {tid} has no task.json")
        try:
            declared = json.loads(spec.read_text(encoding="utf-8")).get("id", tid)
        except (ValueError, AttributeError):
            raise PackageError(f"task {tid}: task.json is not a JSON object") from None
        if declared != tid:
            raise PackageError(f"task {tid}: task.json id does not match its directory")
        selected.append((tid, path))
    return selected


def task_entries(task_dir: Path, include_solutions: bool) -> tuple[list[str], list[str]]:
    """(files to package, skipped paths), both relative to task_dir."""
    packaged: list[str] = []
    skipped: list[str] = []
    for current, dirs, files in os.walk(task_dir):
        here = Path(current)
        top = here == task_dir
        for name in sorted(dirs):
            rel = (here / name).relative_to(task_dir).as_posix()
            if (
                name in SKIP_DIRS
                or (top and name in SKIP_TOP_DIRS)
                or (top and name == "solution" and not include_solutions)
            ):
                skipped.append(rel + "/")
                dirs.remove(name)
            elif (here / name).is_symlink():
                raise PackageError(f"{task_dir.name}/{rel} is a symlink")
        for name in files:
            path = here / name
            rel = path.relative_to(task_dir).as_posix()
            if path.is_symlink():
                raise PackageError(f"{task_dir.name}/{rel} is a symlink")
            if not stat.S_ISREG(path.lstat().st_mode):
                raise PackageError(f"{task_dir.name}/{rel} is not a regular file")
            if name in SECRET_FILES or name.startswith(".env."):
                raise PackageError(f"{task_dir.name}/{rel} looks like a credential or env file")
            if name in SKIP_FILES or name.endswith(SKIP_SUFFIXES):
                skipped.append(rel)
            else:
                packaged.append(rel)
    return sorted(packaged), sorted(skipped)


def _copy(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    dest.chmod(0o755 if src.stat().st_mode & 0o111 else 0o644)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _harness_hash(kit: Path) -> str:
    """Same algorithm as rangebench.cli._get_harness_hash, over the kit."""
    paths = sorted((kit / "rangebench").glob("*.py")) + [kit / "pyproject.toml"]
    h = hashlib.sha256()
    for path in paths:
        h.update(str(path.relative_to(kit)).encode())
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def _task_set_hash(tasks_root: Path) -> str:
    """Same algorithm as rangebench.cli._get_task_set_hash, over the kit's tasks/."""
    h = hashlib.sha256()
    for path in sorted(tasks_root.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        h.update(str(path.relative_to(tasks_root)).encode())
        h.update(b"\0")
        h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def _normalize(info: tarfile.TarInfo) -> tarfile.TarInfo:
    info.uid = info.gid = 0
    info.uname = info.gname = ""
    info.mtime = 0
    info.mode = 0o755 if info.isdir() or info.mode & 0o111 else 0o644
    return info


def _write_archive(kit: Path, output: Path) -> None:
    try:
        raw = output.open("xb")
    except FileExistsError:
        raise PackageError("output already exists; refusing to overwrite") from None
    try:
        with (
            raw,
            gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz,
            tarfile.open(fileobj=gz, mode="w", format=tarfile.PAX_FORMAT) as tar,
        ):
            tar.add(kit, arcname=kit.name, recursive=False, filter=_normalize)
            for path in sorted(kit.rglob("*"), key=lambda p: p.relative_to(kit).as_posix()):
                arcname = f"{kit.name}/{path.relative_to(kit).as_posix()}"
                tar.add(path, arcname=arcname, recursive=False, filter=_normalize)
    except BaseException:
        output.unlink(missing_ok=True)
        raise


def build(
    tasks_dir: Path,
    task_ids: list[str],
    output: Path,
    *,
    include_solutions: bool = False,
    root: Path = ROOT,
) -> dict:
    """Write the kit archive to output and return its suite manifest."""
    if not output.name.endswith(".tar.gz") or not SAFE_NAME.fullmatch(output.name[:-7]):
        raise PackageError("--output must be a NAME.tar.gz file")
    if output.exists() or output.is_symlink():
        raise PackageError("output already exists; refusing to overwrite")
    if not output.parent.is_dir():
        raise PackageError("output directory does not exist")
    files = harness_files(root)
    selected = select_tasks(tasks_dir, task_ids)
    commit = harness_commit(root, files)
    with tempfile.TemporaryDirectory() as tmp:
        kit = Path(tmp) / output.name[:-7]
        for rel in files:
            _copy(root / rel, kit / rel)
        tasks: dict[str, dict[str, str]] = {}
        for tid, src in selected:
            packaged, skipped = task_entries(src, include_solutions)
            dest = kit / "tasks" / tid
            dest.mkdir(parents=True)
            for rel in packaged:
                _copy(src / rel, dest / rel)
            if skipped:
                print(f"note: {tid}: left out {', '.join(skipped)}", file=sys.stderr)
            tasks[tid] = {"identity": task_identity(dest), "source_identity": task_identity(src)}
        run_script = kit / RUN_SCRIPT
        run_script.write_text(RUN_TEMPLATE.format(ids=" ".join(f"'{t}'" for t in task_ids)))
        run_script.chmod(0o755)
        manifest = {
            "suite_manifest_version": 1,
            "task_ids": list(task_ids),
            "solutions_included": include_solutions,
            "harness_commit": commit,
            "harness_source_hash": _harness_hash(kit),
            "task_set_hash": _task_set_hash(kit / "tasks"),
            "tasks": tasks,
            "run_script": RUN_SCRIPT,
            "files": {
                p.relative_to(kit).as_posix(): _sha256(p)
                for p in sorted(kit.rglob("*"), key=lambda p: p.relative_to(kit).as_posix())
                if p.is_file()
            },
        }
        (kit / MANIFEST).write_text(json.dumps(manifest, indent=2) + "\n")
        _write_archive(kit, output)
    return manifest


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--tasks-dir", type=Path, required=True, help="directory holding task dirs")
    ap.add_argument("--output", type=Path, required=True, help="new NAME.tar.gz to write")
    ap.add_argument(
        "--include-solutions", action="store_true", help="also package solution/ (oracle kits)"
    )
    ap.add_argument("task_ids", nargs="+", metavar="ID", help="task directory names to package")
    args = ap.parse_args()
    try:
        manifest = build(
            args.tasks_dir, args.task_ids, args.output, include_solutions=args.include_solutions
        )
    except PackageError as exc:
        raise SystemExit(f"package-suite: {exc}") from None
    print(f"wrote {args.output}: {len(manifest['task_ids'])} tasks")
    print(f"harness source hash: {manifest['harness_source_hash']}")
    print(f"task set hash: {manifest['task_set_hash']}")


if __name__ == "__main__":
    main()
